import { AppConfig } from '@/types/config';

const SYSTEM_PROMPT = `You are an expert app configuration generator. Given a natural language description of an app, you generate a structured JSON configuration that defines the app's data models, pages, and UI components.

Return ONLY valid JSON with this exact structure:
{
  "name": "App Name",
  "description": "Brief description",
  "theme": {
    "primaryColor": "#6366f1",
    "mode": "light",
    "borderRadius": "md"
  },
  "models": [
    {
      "name": "ModelName",
      "label": "Human Label",
      "labelPlural": "Human Labels",
      "fields": [
        {
          "name": "fieldName",
          "type": "text|textarea|number|email|url|date|datetime|boolean|select|multiselect|relation|image",
          "label": "Field Label",
          "required": true,
          "options": [{"label": "Option", "value": "option"}],
          "placeholder": "Enter value...",
          "description": "Helper text"
        }
      ]
    }
  ],
  "pages": [
    {
      "name": "pageName",
      "path": "/page-path",
      "title": "Page Title",
      "icon": "LayoutDashboard",
      "components": [
        {
          "type": "dashboard|table|form|list|card-grid|chart|detail",
          "title": "Component Title",
          "model": "ModelName",
          "fields": [],
          "actions": [
            {"name": "create", "label": "Add New", "type": "create", "variant": "primary"},
            {"name": "edit", "label": "Edit", "type": "edit"},
            {"name": "delete", "label": "Delete", "type": "delete", "variant": "danger"}
          ],
          "widgets": [
            {"type": "stat", "title": "Total Items", "model": "ModelName", "aggregation": "count", "icon": "Package", "color": "#6366f1"}
          ]
        }
      ]
    }
  ],
  "navigation": {
    "items": [
      {"label": "Dashboard", "path": "/dashboard", "icon": "LayoutDashboard"},
      {"label": "ModelName", "path": "/page-path", "icon": "Database"}
    ]
  },
  "features": {
    "auth": true,
    "csvImport": true,
    "githubExport": true,
    "notifications": true
  }
}

Rules:
- Always include a dashboard page with stat widgets
- Every model should have a page with a table and form components
- Use sensible field types
- Always include id-like, name, and timestamp fields
- Return ONLY JSON, no markdown, no explanation
- Make it complete and realistic for the described app`;

export async function generateAppConfig(prompt: string): Promise<{
  config: AppConfig | null;
  rawJson: string;
  error: string | null;
}> {
  try {
    const response = await fetch('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-api-key': process.env.ANTHROPIC_API_KEY!,
        'anthropic-version': '2023-06-01',
      },
      body: JSON.stringify({
        model: 'claude-3-5-sonnet-20241022',
        max_tokens: 4096,
        system: SYSTEM_PROMPT,
        messages: [
          {
            role: 'user',
            content: `Generate a complete app configuration JSON for: ${prompt}`,
          },
        ],
      }),
    });

    if (!response.ok) {
      throw new Error(`AI API error: ${response.statusText}`);
    }

    const data = await response.json();
    const rawJson = data.content?.[0]?.text ?? '';

    // Parse the JSON
    const cleaned = rawJson
      .replace(/^```json\s*/i, '')
      .replace(/^```\s*/i, '')
      .replace(/```\s*$/i, '')
      .trim();

    const config = JSON.parse(cleaned) as AppConfig;

    return { config, rawJson: cleaned, error: null };
  } catch (error) {
    console.error('Config generation error:', error);
    return {
      config: null,
      rawJson: '',
      error: error instanceof Error ? error.message : 'Failed to generate config',
    };
  }
}

// Generate GitHub export content
export async function generateGithubExport(config: AppConfig): Promise<string> {
  const readme = `# ${config.name}

${config.description || ''}

## Generated by AppForge

This application was generated using AppForge's AI-powered app generator.

## Models

${config.models.map((m) => `### ${m.label || m.name}
Fields: ${m.fields.map((f) => `${f.label || f.name} (${f.type})`).join(', ')}`).join('\n\n')}

## Pages

${config.pages.map((p) => `- **${p.title || p.name}** — \`${p.path}\``).join('\n')}

## Tech Stack
- Next.js 15
- TypeScript
- TailwindCSS
- PostgreSQL + Prisma
- NextAuth.js

## Getting Started

\`\`\`bash
npm install
npm run db:push
npm run dev
\`\`\`
`;
  return readme;
}
