import { NextRequest, NextResponse } from 'next/server';
import { auth } from '@/lib/auth';
import { prisma } from '@/lib/prisma';
import { AppConfig, ModelConfig, FieldConfig } from '@/types/config';

type Params = { params: Promise<{ appId: string }> };

function generatePrismaSchema(config: AppConfig): string {
  const models = config.models
    .map((model: ModelConfig) => {
      const fields = model.fields
        .map((f: FieldConfig) => {
          let prismaType = 'String';
          let modifier = '?';
          if (f.required) modifier = '';

          switch (f.type) {
            case 'number': prismaType = 'Float'; break;
            case 'boolean': prismaType = 'Boolean'; break;
            case 'date':
            case 'datetime': prismaType = 'DateTime'; break;
            case 'json':
            case 'multiselect': prismaType = 'Json'; break;
            default: prismaType = 'String'; break;
          }

          return `  ${f.name} ${prismaType}${modifier}`;
        })
        .join('\n');

      return `model ${model.name} {
  id        String   @id @default(cuid())
${fields}
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
}`;
    })
    .join('\n\n');

  return `// Generated by AppForge
// https://appforge.dev

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

${models}`;
}

function generateReadme(config: AppConfig): string {
  return `# ${config.name}

> ${config.description || 'Generated with AppForge'}

## Overview

This application was generated by [AppForge](https://appforge.dev) — an AI-powered app generator built on Next.js, TypeScript, and PostgreSQL.

## Data Models

${config.models
  .map(
    (m: ModelConfig) => `### ${m.label || m.name}

| Field | Type | Required |
|-------|------|----------|
${m.fields.map((f: FieldConfig) => `| ${f.label || f.name} | ${f.type} | ${f.required ? '✓' : '—'} |`).join('\n')}`
  )
  .join('\n\n')}

## Pages

${config.pages.map((p) => `- **${p.title || p.name}** (\`${p.path}\``).join('\n')}

## Tech Stack

- **Frontend**: Next.js 15 + React 18 + TypeScript + TailwindCSS
- **Backend**: Next.js API Routes
- **Database**: PostgreSQL + Prisma ORM
- **Auth**: NextAuth.js (Google + GitHub)
- **Deploy**: Vercel + Neon

## Getting Started

\`\`\`bash
# 1. Clone the repository
git clone <your-repo-url>
cd ${config.name.toLowerCase().replace(/\s+/g, '-')}

# 2. Install dependencies
npm install

# 3. Set up environment variables
cp .env.example .env.local
# Fill in your DATABASE_URL, NEXTAUTH_SECRET, etc.

# 4. Set up database
npx prisma db push

# 5. Start development server
npm run dev
\`\`\`

## Environment Variables

\`\`\`env
DATABASE_URL=postgresql://...
NEXTAUTH_SECRET=your-secret
NEXTAUTH_URL=http://localhost:3000
GOOGLE_CLIENT_ID=...
GOOGLE_CLIENT_SECRET=...
GITHUB_CLIENT_ID=...
GITHUB_CLIENT_SECRET=...
ANTHROPIC_API_KEY=...
\`\`\`

---

*Generated by AppForge on ${new Date().toLocaleDateString()}*
`;
}

function generateEnvExample(): string {
  return `# Database
DATABASE_URL=postgresql://username:password@host:5432/dbname

# NextAuth
NEXTAUTH_SECRET=your-super-secret-key-min-32-chars
NEXTAUTH_URL=http://localhost:3000

# Google OAuth
GOOGLE_CLIENT_ID=your-google-client-id
GOOGLE_CLIENT_SECRET=your-google-client-secret

# GitHub OAuth
GITHUB_CLIENT_ID=your-github-client-id
GITHUB_CLIENT_SECRET=your-github-client-secret

# Anthropic AI
ANTHROPIC_API_KEY=your-anthropic-api-key
`;
}

export async function GET(_req: NextRequest, { params }: Params) {
  try {
    const session = await auth();
    if (!session?.user?.id) {
      return NextResponse.json({ success: false, error: 'Unauthorized' }, { status: 401 });
    }

    const { appId } = await params;
    const app = await prisma.app.findFirst({ where: { id: appId, userId: session.user.id } });
    if (!app) {
      return NextResponse.json({ success: false, error: 'App not found' }, { status: 404 });
    }

    const config = app.config as AppConfig;

    const exportFiles = {
      'README.md': generateReadme(config),
      'prisma/schema.prisma': generatePrismaSchema(config),
      '.env.example': generateEnvExample(),
      'app.config.json': JSON.stringify(config, null, 2),
    };

    return NextResponse.json({
      success: true,
      data: {
        appName: app.name,
        files: exportFiles,
        repoName: app.name.toLowerCase().replace(/\s+/g, '-'),
      },
    });
  } catch (error) {
    console.error('GitHub export error:', error);
    return NextResponse.json({ success: false, error: 'Internal server error' }, { status: 500 });
  }
}
